import React from "react";

//포스실드, 소울링 (100)
const FsPotentialData = [
    {
        "grade": "rare",
        "effects": [
            {
                "first": [
                    {
                        "str":12
                    },
                    {
                        "dex":12
                    },
                    {
                        "int":12
                    },
                    {
                        "luk":12
                    },
                    {
                        "hp":100
                    },
                    {
                        "atk":12
                    },
                    {
                        "mAtk":12
                    },
                    {
                        "strP":3
                    },
                    {
                        "dexP":3
                    },
                    {
                        "intP":3
                    },
                    {
                        "lukP":3
                    },
                    {
                        "atkP":3
                    },
                    {
                        "mAtkP":3
                    },
                    {
                        "crit":4
                    },
                    {
                        "dmg":3
                    },
                    {
                        "allStat":5
                    },
                    {
                        //공격 시 20% 확률로 200의 HP 회복
                    },
                    {
                        //공격 시 20% 확률로 110의 MP 회복
                    },
                    {
                        //공격 시 20% 확률로 5레벨 중독효과 적용
                    },
                    {
                         //공격 시 10% 확률로 2레벨 기절효과 적용
                    },
                    {
                        //공격 시 20% 확률로 2레벨 슬로우효과 적용
                    },
                    {
                        //공격 시 20% 확률로 2레벨 암흑효과 적용
                    },
                    {
                        //공격 시 10% 확률로 2레벨 빙결효과 적용
                    },
                    {
                        //공격 시 10% 확률로 2레벨 봉인효과 적용
                    },
                    {
                        "ignoreDef":15
                    }
                ]
            },
            {
                "second": [
                    {
                       "str":6
                    },
                    {
                        "dex":6
                    },
                    {
                        "int":6
                    },
                    {
                        "luk":6
                    },
                    {
                        "hp":50
                    },
                    {
                        "atk":6
                    },
                    {
                        "mAtk":6
                    },
                    {
                        "str":12
                    },
                    {
                        "dex":12
                    },
                    {
                        "int":12
                    },
                    {
                        "luk":12
                    },
                    {
                        "hp":100
                    },
                    {
                        "atk":12
                    },
                    {
                        "mAtk":12
                    },
                    {
                        "strP":3
                    },
                    {
                        "dexP":3
                    },
                    {
                        "intP":3
                    },
                    {
                        "lukP":3
                    },
                    {
                        "hpP":3
                    },
                    {
                        "mpP":3
                    },
                    {
                        "atkP":3
                    },
                    {
                        "mAtkP":3
                    },
                    {
                        "allStat":5
                    },
                    {
                        //공격 시 20% 확률로 200의 HP 회복
                    },
                    {
                        //공격 시 20% 확률로 110의 MP 회복
                    },
                    {
                        //공격 시 20% 확률로 5레벨 중독효과 적용
                    },
                    {
                        //공격 시 10% 확률로 2레벨 기절효과 적용
                    },
                    {
                        //공격 시 20% 확률로 2레벨 슬로우효과 적용
                    },
                    {
                        //공격 시 20% 확률로 2레벨 암흑효과 적용
                    },
                    {
                       //공격 시 10% 확률로 2레벨 빙결효과 적용
                    },
                    {
                        //공격 시 10% 확률로 2레벨 봉인효과 적용
                    },
                    {
                        "ignoreDef":15
                    }
                ]
            }
        ]
    },
    {
        "grade": "epic",
        "effects": [
            {
                "first": [
                    {
                        "strP":6
                    },
                    {
                        "dexP":6
                    },
                    {
                        "intP":6
                    },
                    {
                        "lukP":6
                    },
                    {
                        "hpP":6
                    },
                    {
                        "atkP":6
                    },
                    {
                        "mAtkP":6
                    },
                    {
                        "crit":8
                    },
                    {
                        "dmg":6
                    },
                    {
                        "allStatP":3
                    },
                    {
                        //공격 시 20% 확률로 300의 HP 회복
                    },
                    {
                       //공격 시 20% 확률로 165의 MP 회복
                    },
                    {
                        "ignoreDef":15
                    }
                ]
            },
            {
                "second": [
                    {
                        "str":12
                    },
                    {
                        "dex":12
                    },
                    {
                        "int":12
                    },
                    {
                        "luk":12
                    },
                    {
                        "hp":100
                    },
                    {
                        "atk":12
                    },
                    {
                        "mAtk":12
                    },
                    {
                        "strP":3
                    },
                    {
                        "dexP":3
                    },
                    {
                        "intP":3
                    },
                    {
                        "lukP":3
                    },
                    {
                        "hpP":3
                    },
                    {
                        "mpP":3
                    },
                    {
                        "atkP":3
                    },
                    {
                        "mAtkP":3
                    },
                    {
                        "crit":4
                    },
                    {
                        "dmg":3
                    },
                    {
                        "allStat":5
                    },
                    {
                        "strP":6
                    },
                    {
                        "dexP":6
                    },
                    {
                        "intP":6
                    },
                    {
                        "lukP":6
                    },
                    {
                        "hpP":6
                    },
                    {
                        "atkP":6
                    },
                    {
                        "mAtkP":6
                    },
                    {
                        "crit":8
                    },
                    {
                        "dmg":6
                    },
                    {
                        "allStatP":3
                    },
                    {
                        //공격 시 20% 확률로 200의 HP 회복
                    },
                    {
                        //공격 시 20% 확률로 110의 MP 회복
                    },
                    {
                        //공격 시 20% 확률로 5레벨 중독효과 적용
                    },
                    {
                        //공격 시 10% 확률로 2레벨 기절효과 적용
                    },
                    {
                        //공격 시 20% 확률로 2레벨 슬로우효과 적용
                    },
                    {
                        //공격 시 20% 확률로 2레벨 암흑효과 적용
                    },
                    {
                        //공격 시 10% 확률로 2레벨 빙결효과 적용
                    },
                    {
                        //공격 시 10% 확률로 2레벨 봉인효과 적용
                    },
                    {
                        "ignoreDef":15
                    },
                    {
                        //공격 시 20% 확률로 300의 HP 회복
                    },
                    {
                        //공격 시 20% 확률로 165의 MP 회복
                    }
                ]
            }
        ]
    },
    {
        "grade": "unique",
        "effects": [
            {
                "first": [
                    {
                        "strP":9
                    },
                    {
                        "dexP":9
                    },
                    {
                        "intP":9
                    },
                    {
                        "lukP":9
                    },
                    {
                        "atkP":9
                    },
                    {
                        "mAtkP":9
                    },
                    {
                        "crit":9
                    },
                    {
                        "dmg":9
                    },
                    {
                        "allStatP":6
                    },
                    {
                        "ignoreDef":30
                    },
                    {
                        "bossDmg":30
                    }
                ]
            },
            {
                "second": [
                    {
                        "strP":6
                    },
                    {
                        "dexP":6
                    },
                    {
                        "intP":6
                    },
                    {
                        "lukP":6
                    },
                    {
                        "hpP":6
                    },
                    {
                        "atkP":6
                    },
                    {
                        "mAtk":6
                    },
                    {
                        "crit":8
                    },
                    {
                        "dmg":6
                    },
                    {
                        "allStatP":3
                    },
                    {
                        "strP":9
                    },
                    {
                        "dexP":9
                    },
                    {
                        "intP":9
                    },
                    {
                        "lukP":9
                    },
                    {
                        "atkP":9
                    },
                    {
                        "mAtk":9
                    },
                    {
                        "crit":9
                    },
                    {
                        "dmg":9
                    },
                    {
                        "allStatP":6
                    },
                    {
                        //공격 시 20% 확률로 300의 HP 회복
                    },
                    {
                        //공격 시 20% 확률로 165의 MP 회복
                    },
                    {
                        "ignoreDef":15
                    },
                    {
                        "ignoreDef":30
                    },
                    {
                        "bossDmg":30
                    },
                    {
                        //피격 시 5% 확률로 데미지의 20% 무시
                    },
                    {
                        //피격 시 5% 확률로 데미지의 40% 무시
                    }
                ]
            }
        ]
    },
    {
        "grade": "legendary",
        "effects": [
            {
                "first": [
                    {
                        "strP":12
                    },
                    {
                        "dexP":12
                    },
                    {
                        "intP":12
                    },
                    {
                        "lukP":12
                    },
                    {
                        "atkP":12
                    },
                    {
                        "mAtkP":12
                    },
                    {
                        "crit":12
                    },
                    {
                        "dmg":12
                    },
                    {
                        "allStatP":9
                    },
                    {
                        "atk":32
                    },
                    {
                        "mAtk":32
                    },
                    {
                        "ignoreDef":35
                    },
                    {
                        "ignoreDef":40
                    },
                    {
                        "bossDmg":35
                    },
                    {
                        "bossDmg":40
                    },
                    {
                        //피격 시 10% 확률로 데미지의 20% 무시
                    },
                    {
                        //피격 시 10% 확률로 데미지의 40% 무시
                    }
                ]
            },
            {
                "second": [
                    {
                        "strP":9
                    },
                    {
                        "dexP":9
                    },
                    {
                        "intP":9
                    },
                    {
                        "lukP":9
                    },
                    {
                        "atkP":9
                    },
                    {
                        "mAtkP":9
                    },
                    {
                        "crit":9
                    },
                    {
                        "dmg":9
                    },
                    {
                        "allStatP":6
                    },
                    {
                        "strP":12
                    },
                    {
                        "dexP":12
                    },
                    {
                        "intP":12
                    },
                    {
                        "lukP":12
                    },
                    {
                        "atkP":12
                    },
                    {
                        "mAtkP":12
                    },
                    {
                        "crit":12
                    },
                    {
                        "dmg":12
                    },
                    {
                        "allStatP":9
                    },
                    {
                        "atk":32
                    },
                    {
                        "mAtk":32
                    },
                    {
                        "ignoreDef":30
                    },
                    {
                        "ignoreDef":35
                    },
                    {
                        "ignoreDef":40
                    },
                    {
                        "bossDmg":30
                    },
                    {
                        "bossDmg":35
                    },
                    {
                        "bossDmg":40
                    },
                    {
                        //피격 시 5% 확률로 데미지의 20% 무시
                    },
                    {
                        //피격 시 5% 확률로 데미지의 40% 무시
                    },
                    {
                        //피격 시 10% 확률로 데미지의 20% 무시
                    },
                    {
                        //피격 시 10% 확률로 데미지의 40% 무시
                    }
                ]
            }
        ]
    }
];

export default FsPotentialData;