export const DefaultItems = [
  {
    label: "하이네스 어새신보닛",
    name: "하이네스 어새신보닛",
    imageUrl: "https://avatar.maplestory.nexon.com/ItemIcon/KEPCIPOB.png",
    category: "모자",
    upgrade: 0,
    base: {
      dex: 40,
      luk: 40,
      hp: 360,
      mp: 360,
      atk: 2,
      def: 300,
      ignoreDef: 10,
    },
    scroll: {},
    grade: "nothing",
    star: 0,
    flame: {},
    scissors: 10,
  },
  {
    label: "아케인셰이드 보우",
    name: "아케인셰이드 보우",
    class: "궁수",
    imageUrl: "https://avatar.maplestory.nexon.com/ItemIcon/KELHJFIE.png",
    category: "활 (두손무기)",
    upgrade: 0,
    base: {
      str: 100,
      dex: 100,
      atk: 276,
      speed: 19,
      bossDmg: 30,
      ignoreDef: 20,
    },
    scroll: {},
    grade: "none",
    star: 0,
    flame: {},
    soul: {},
    scissors: 10,
  },
  {
    name: "앱솔랩스 아처슈즈",
    imageUrl: "https://avatar.maplestory.nexon.com/ItemIcon/KEPFIHNB.png",
    category: "신발",
    upgrade: 0,
    base: {
      str: 20,
      dex: 20,
      atk: 5,
      def: 150,
      speed: 10,
      jump: 7,
    },
    scroll: {},
    grade: "nothing",
    star: 0,
    flame: {},
    scissors: 10,
  },
  {
    label: "하이네스 어새신보닛",
    name: "하이네스 어새신보닛",
    imageUrl: "https://avatar.maplestory.nexon.com/ItemIcon/KEPCIPOB.png",
    category: "모자",
    upgrade: 0,
    base: {
      dex: 40,
      luk: 40,
      hp: 360,
      mp: 360,
      atk: 2,
      def: 300,
      ignoreDef: 10,
    },
    scroll: {},
    grade: "nothing",
    star: 0,
    flame: {},
    scissors: 10,
  },
  {
    label: "아케인셰이드 보우",
    name: "아케인셰이드 보우",
    class: "궁수",
    imageUrl: "https://avatar.maplestory.nexon.com/ItemIcon/KELHJFIE.png",
    category: "활 (두손무기)",
    upgrade: 0,
    base: {
      str: 100,
      dex: 100,
      atk: 276,
      speed: 19,
      bossDmg: 30,
      ignoreDef: 20,
    },
    scroll: {},
    grade: "none",
    star: 0,
    flame: {},
    soul: {},
    scissors: 10,
  },
  {
    name: "앱솔랩스 아처슈즈",
    imageUrl: "https://avatar.maplestory.nexon.com/ItemIcon/KEPFIHNB.png",
    category: "신발",
    upgrade: 0,
    base: {
      str: 20,
      dex: 20,
      atk: 5,
      def: 150,
      speed: 10,
      jump: 7,
    },
    scroll: {},
    grade: "nothing",
    star: 0,
    flame: {},
    scissors: 10,
  },
  {
    label: "하이네스 어새신보닛",
    name: "하이네스 어새신보닛",
    imageUrl: "https://avatar.maplestory.nexon.com/ItemIcon/KEPCIPOB.png",
    category: "모자",
    upgrade: 0,
    base: {
      dex: 40,
      luk: 40,
      hp: 360,
      mp: 360,
      atk: 2,
      def: 300,
      ignoreDef: 10,
    },
    scroll: {},
    grade: "nothing",
    star: 0,
    flame: {},
    scissors: 10,
  },
  {
    label: "아케인셰이드 보우",
    name: "아케인셰이드 보우",
    class: "궁수",
    imageUrl: "https://avatar.maplestory.nexon.com/ItemIcon/KELHJFIE.png",
    category: "활 (두손무기)",
    upgrade: 0,
    base: {
      str: 100,
      dex: 100,
      atk: 276,
      speed: 19,
      bossDmg: 30,
      ignoreDef: 20,
    },
    scroll: {},
    grade: "none",
    star: 0,
    flame: {},
    soul: {},
    scissors: 10,
  },
  {
    name: "앱솔랩스 아처슈즈",
    imageUrl: "https://avatar.maplestory.nexon.com/ItemIcon/KEPFIHNB.png",
    category: "신발",
    upgrade: 0,
    base: {
      str: 20,
      dex: 20,
      atk: 5,
      def: 150,
      speed: 10,
      jump: 7,
    },
    scroll: {},
    grade: "nothing",
    star: 0,
    flame: {},
    scissors: 10,
  },
  {
    label: "하이네스 어새신보닛",
    name: "하이네스 어새신보닛",
    imageUrl: "https://avatar.maplestory.nexon.com/ItemIcon/KEPCIPOB.png",
    category: "모자",
    upgrade: 0,
    base: {
      dex: 40,
      luk: 40,
      hp: 360,
      mp: 360,
      atk: 2,
      def: 300,
      ignoreDef: 10,
    },
    scroll: {},
    grade: "nothing",
    star: 0,
    flame: {},
    scissors: 10,
  },
  {
    label: "아케인셰이드 보우",
    name: "아케인셰이드 보우",
    class: "궁수",
    imageUrl: "https://avatar.maplestory.nexon.com/ItemIcon/KELHJFIE.png",
    category: "활 (두손무기)",
    upgrade: 0,
    base: {
      str: 100,
      dex: 100,
      atk: 276,
      speed: 19,
      bossDmg: 30,
      ignoreDef: 20,
    },
    scroll: {},
    grade: "none",
    star: 0,
    flame: {},
    soul: {},
    scissors: 10,
  },
  {
    name: "앱솔랩스 아처슈즈",
    imageUrl: "https://avatar.maplestory.nexon.com/ItemIcon/KEPFIHNB.png",
    category: "신발",
    upgrade: 0,
    base: {
      str: 20,
      dex: 20,
      atk: 5,
      def: 150,
      speed: 10,
      jump: 7,
    },
    scroll: {},
    grade: "nothing",
    star: 0,
    flame: {},
    scissors: 10,
  },
  {
    label: "하이네스 어새신보닛",
    name: "하이네스 어새신보닛",
    imageUrl: "https://avatar.maplestory.nexon.com/ItemIcon/KEPCIPOB.png",
    category: "모자",
    upgrade: 0,
    base: {
      dex: 40,
      luk: 40,
      hp: 360,
      mp: 360,
      atk: 2,
      def: 300,
      ignoreDef: 10,
    },
    scroll: {},
    grade: "nothing",
    star: 0,
    flame: {},
    scissors: 10,
  },
  {
    label: "아케인셰이드 보우",
    name: "아케인셰이드 보우",
    class: "궁수",
    imageUrl: "https://avatar.maplestory.nexon.com/ItemIcon/KELHJFIE.png",
    category: "활 (두손무기)",
    upgrade: 0,
    base: {
      str: 100,
      dex: 100,
      atk: 276,
      speed: 19,
      bossDmg: 30,
      ignoreDef: 20,
    },
    scroll: {},
    grade: "none",
    star: 0,
    flame: {},
    soul: {},
    scissors: 10,
  },
  {
    name: "앱솔랩스 아처슈즈",
    imageUrl: "https://avatar.maplestory.nexon.com/ItemIcon/KEPFIHNB.png",
    category: "신발",
    upgrade: 0,
    base: {
      str: 20,
      dex: 20,
      atk: 5,
      def: 150,
      speed: 10,
      jump: 7,
    },
    scroll: {},
    grade: "nothing",
    star: 0,
    flame: {},
    scissors: 10,
  },
  {
    label: "하이네스 어새신보닛",
    name: "하이네스 어새신보닛",
    imageUrl: "https://avatar.maplestory.nexon.com/ItemIcon/KEPCIPOB.png",
    category: "모자",
    upgrade: 0,
    base: {
      dex: 40,
      luk: 40,
      hp: 360,
      mp: 360,
      atk: 2,
      def: 300,
      ignoreDef: 10,
    },
    scroll: {},
    grade: "nothing",
    star: 0,
    flame: {},
    scissors: 10,
  },
  {
    label: "아케인셰이드 보우",
    name: "아케인셰이드 보우",
    class: "궁수",
    imageUrl: "https://avatar.maplestory.nexon.com/ItemIcon/KELHJFIE.png",
    category: "활 (두손무기)",
    upgrade: 0,
    base: {
      str: 100,
      dex: 100,
      atk: 276,
      speed: 19,
      bossDmg: 30,
      ignoreDef: 20,
    },
    scroll: {},
    grade: "none",
    star: 0,
    flame: {},
    soul: {},
    scissors: 10,
  },
  {
    name: "앱솔랩스 아처슈즈",
    imageUrl: "https://avatar.maplestory.nexon.com/ItemIcon/KEPFIHNB.png",
    category: "신발",
    upgrade: 0,
    base: {
      str: 20,
      dex: 20,
      atk: 5,
      def: 150,
      speed: 10,
      jump: 7,
    },
    scroll: {},
    grade: "nothing",
    star: 0,
    flame: {},
    scissors: 10,
  },
  {
    label: "하이네스 어새신보닛",
    name: "하이네스 어새신보닛",
    imageUrl: "https://avatar.maplestory.nexon.com/ItemIcon/KEPCIPOB.png",
    category: "모자",
    upgrade: 0,
    base: {
      dex: 40,
      luk: 40,
      hp: 360,
      mp: 360,
      atk: 2,
      def: 300,
      ignoreDef: 10,
    },
    scroll: {},
    grade: "nothing",
    star: 0,
    flame: {},
    scissors: 10,
  },
  {
    label: "아케인셰이드 보우",
    name: "아케인셰이드 보우",
    class: "궁수",
    imageUrl: "https://avatar.maplestory.nexon.com/ItemIcon/KELHJFIE.png",
    category: "활 (두손무기)",
    upgrade: 0,
    base: {
      str: 100,
      dex: 100,
      atk: 276,
      speed: 19,
      bossDmg: 30,
      ignoreDef: 20,
    },
    scroll: {},
    grade: "none",
    star: 0,
    flame: {},
    soul: {},
    scissors: 10,
  },
  {
    name: "앱솔랩스 아처슈즈",
    imageUrl: "https://avatar.maplestory.nexon.com/ItemIcon/KEPFIHNB.png",
    category: "신발",
    upgrade: 0,
    base: {
      str: 20,
      dex: 20,
      atk: 5,
      def: 150,
      speed: 10,
      jump: 7,
    },
    scroll: {},
    grade: "nothing",
    star: 0,
    flame: {},
    scissors: 10,
  },
  {
    label: "하이네스 어새신보닛",
    name: "하이네스 어새신보닛",
    imageUrl: "https://avatar.maplestory.nexon.com/ItemIcon/KEPCIPOB.png",
    category: "모자",
    upgrade: 0,
    base: {
      dex: 40,
      luk: 40,
      hp: 360,
      mp: 360,
      atk: 2,
      def: 300,
      ignoreDef: 10,
    },
    scroll: {},
    grade: "nothing",
    star: 0,
    flame: {},
    scissors: 10,
  },
  {
    label: "아케인셰이드 보우",
    name: "아케인셰이드 보우",
    class: "궁수",
    imageUrl: "https://avatar.maplestory.nexon.com/ItemIcon/KELHJFIE.png",
    category: "활 (두손무기)",
    upgrade: 0,
    base: {
      str: 100,
      dex: 100,
      atk: 276,
      speed: 19,
      bossDmg: 30,
      ignoreDef: 20,
    },
    scroll: {},
    grade: "none",
    star: 0,
    flame: {},
    soul: {},
    scissors: 10,
  },
  {
    name: "앱솔랩스 아처슈즈",
    imageUrl: "https://avatar.maplestory.nexon.com/ItemIcon/KEPFIHNB.png",
    category: "신발",
    upgrade: 0,
    base: {
      str: 20,
      dex: 20,
      atk: 5,
      def: 150,
      speed: 10,
      jump: 7,
    },
    scroll: {},
    grade: "nothing",
    star: 0,
    flame: {},
    scissors: 10,
  },
];
