export const DefaultItems = [
  {
    label: "골든 클로버 벨트",
    value: "골든 클로버 벨트",
    name: "골든 클로버 벨트",
    imageUrl: "https://avatar.maplestory.nexon.com/ItemIcon/KEOBJFJD.png",
    category: "벨트",
    upgrade: 0,
    base: {
      str: 15,
      dex: 15,
      int: 15,
      luk: 15,
      hp: 150,
      mp: 150,
      atk: 1,
      mAtk: 1,
      def: 150,
    },
    scroll: {},
    grade: "nothing",
    star: 0,
    flame: {},
  },
  {
    label: "하이네스 어새신보닛",
    value: "하이네스 어새신보닛",
    name: "하이네스 어새신보닛",
    imageUrl: "https://avatar.maplestory.nexon.com/ItemIcon/KEPCIPOB.png",
    category: "모자",
    upgrade: 0,
    base: {
      dex: 40,
      luk: 40,
      hp: 360,
      mp: 360,
      atk: 2,
      def: 300,
      ignoreDef: 10,
    },
    scroll: {},
    grade: "nothing",
    star: 0,
    flame: {},
    scissors: 10,
  },
  {
    label: "아케인셰이드 보우",
    value: "아케인셰이드 보우",
    name: "아케인셰이드 보우",
    class: "궁수",
    imageUrl: "https://avatar.maplestory.nexon.com/ItemIcon/KELHJFIE.png",
    category: "활 (두손무기)",
    upgrade: 0,
    base: {
      str: 100,
      dex: 100,
      atk: 276,
      speed: 19,
      bossDmg: 30,
      ignoreDef: 20,
    },
    scroll: {},
    grade: "none",
    star: 0,
    flame: {},
    soul: {},
    scissors: 10,
  },
  {
    name: "앱솔랩스 아처슈즈",
    imageUrl: "https://avatar.maplestory.nexon.com/ItemIcon/KEPFIHNB.png",
    category: "신발",
    upgrade: 0,
    base: {
      str: 20,
      dex: 20,
      atk: 5,
      def: 150,
      speed: 10,
      jump: 7,
    },
    scroll: {},
    grade: "nothing",
    star: 0,
    flame: {},
    scissors: 10,
  },

  {
    name: "이터널 플레임 링",
    imageUrl: "https://avatar.maplestory.nexon.com/ItemIcon/KEODPEMF.png",
    category: "반지",
    upgrade: 0,
    base: {
      str: 40,
      dex: 40,
      int: 40,
      luk: 40,
      hp: 4000,
      mp: 4000,
      atk: 25,
      mAtk: 25,
    },
    scroll: {},
    grade: "unique",
    star: 0,
    potential: {
      grade: "unique",
      effects: [
        {
          strP: 9,
        },
        {
          allStatP: 3,
        },
        {
          mpP: 6,
        },
      ],
    },
    flame: {},
  },
  {
    name: "하이네스 원더러햇",
    imageUrl: "https://avatar.maplestory.nexon.com/ItemIcon/KEPCIPOA.png",
    category: "모자",
    upgrade: 0,
    base: {
      str: 40,
      dex: 40,
      hp: 360,
      mp: 360,
      atk: 2,
      def: 300,
      ignoreDef: 10,
    },
    scroll: {
      str: 62,
      dex: 62,
      hp: 255,
      atk: 19,
      mAtk: 19,
      def: 402,
    },
    grade: "epic",
    star: 17,
    potential: {
      grade: "epic",
      effects: [
        {
          strP: 6,
        },
        {
          luk: 12,
        },
        {
          str: 12,
        },
      ],
    },
    flame: {
      str: 20,
      int: 20,
      luk: 40,
      hp: 2250,
      mp: 2250,
    },
    scissors: 10,
  },
  {
    name: "골드 메이플리프 엠블렘",
    imageUrl: "https://avatar.maplestory.nexon.com/ItemIcon/KEOLLEOA.png",
    category: "엠블렘",
    upgrade: 0,
    base: {
      str: 10,
      dex: 10,
      int: 10,
      luk: 10,
      atk: 2,
      mAtk: 2,
    },
    scroll: {},
    grade: "unique",
    star: 0,
    potential: {
      grade: "unique",
      effects: [
        {
          atkP: 9,
        },
        {
          lukP: 6,
        },
      ],
    },
    flame: {},
  },
  {
    name: "응축된 힘의 결정석",
    imageUrl: "https://avatar.maplestory.nexon.com/ItemIcon/KEPDJDJJ.png",
    category: "얼굴장식",
    upgrade: 0,
    base: {
      str: 5,
      dex: 5,
      int: 5,
      luk: 5,
      atk: 5,
      mAtk: 5,
      def: 100,
    },
    scroll: {
      str: 25,
      dex: 25,
      int: 25,
      luk: 25,
      def: 70,
    },
    grade: "epic",
    star: 10,
    potential: {
      grade: "epic",
      effects: [
        {
          strP: 6,
        },
        {
          luk: 12,
        },
        {
          strP: 3,
        },
      ],
    },
    flame: {
      int: 15,
      luk: 15,
      hp: 1650,
      atk: 3,
      def: 18,
    },
  },
  {
    name: "크리스탈 웬투스 뱃지",
    imageUrl: "https://avatar.maplestory.nexon.com/ItemIcon/KEOKJHGG.png",
    category: "뱃지",
    upgrade: 0,
    base: {
      str: 10,
      dex: 10,
      int: 10,
      luk: 10,
      atk: 5,
      mAtk: 5,
      speed: 10,
      jump: 10,
    },
    scroll: {},
    grade: "nothing",
    star: 0,
    flame: {},
  },
  {
    name: "블랙빈 마크",
    imageUrl: "https://avatar.maplestory.nexon.com/ItemIcon/KEPAJFND.png",
    category: "눈장식",
    upgrade: 0,
    base: {
      str: 7,
      dex: 7,
      int: 7,
      luk: 7,
      atk: 1,
      mAtk: 1,
      def: 120,
    },
    scroll: {
      str: 54,
      dex: 54,
      int: 54,
      luk: 54,
      atk: 15,
      mAtk: 15,
      def: 170,
    },
    grade: "unique",
    star: 17,
    potential: {
      grade: "unique",
      effects: [
        {
          hpHeal: 30,
        },
        {
          strP: 6,
        },
        {
          strP: 6,
        },
      ],
    },
    flame: {
      str: 32,
      dex: 16,
      int: 20,
      luk: 36,
      allStatP: 5,
    },
  },
  {
    name: "지옥의 불꽃",
    imageUrl: "https://avatar.maplestory.nexon.com/ItemIcon/KEPBJGNH.png",
    category: "귀고리",
    upgrade: 0,
    base: {
      str: 7,
      dex: 7,
      int: 7,
      luk: 7,
      hp: 100,
      mp: 100,
      atk: 2,
      mAtk: 2,
      def: 100,
    },
    scroll: {
      str: 25,
      dex: 25,
      int: 25,
      luk: 25,
      def: 70,
    },
    grade: "nothing",
    star: 10,
    flame: {
      dex: 24,
      luk: 24,
      hp: 1950,
      speed: 5,
      allStatP: 5,
    },
  },
  {
    name: "리부트 테네브리스 원정대 반지(완성)",
    imageUrl: "https://avatar.maplestory.nexon.com/ItemIcon/KEODPEPA.png",
    category: "반지",
    upgrade: 0,
    base: {
      str: 40,
      dex: 40,
      int: 40,
      luk: 40,
      hp: 4000,
      mp: 4000,
      atk: 25,
      mAtk: 25,
    },
    scroll: {},
    grade: "epic",
    star: 0,
    potential: {
      grade: "epic",
      effects: [
        {
          strP: 6,
        },
        {
          mp: 120,
        },
        {
          lukP: 3,
        },
      ],
    },
    flame: {},
  },
  {
    name: "앱솔랩스 블로우너클",
    imageUrl: "https://avatar.maplestory.nexon.com/ItemIcon/KELKJFMD.png",
    category: "너클 (두손무기)",
    upgrade: 0,
    base: {
      str: 60,
      dex: 60,
      atk: 154,
      bossDmg: 30,
      ignoreDef: 10,
    },
    scroll: {
      str: 66,
      dex: 66,
      hp: 255,
      mp: 255,
      atk: 81,
    },
    grade: "unique",
    star: 17,
    potential: {
      grade: "unique",
      effects: [
        {
          dmg: 9,
        },
        {
          bossDmg: 35,
        },
        {
          crit: 10,
        },
      ],
    },
    flame: {
      mp: 1440,
      atk: 47,
      def: 27,
      bossDmg: 10,
    },
  },
  {
    name: "이글아이 원더러코트",
    imageUrl: "https://avatar.maplestory.nexon.com/ItemIcon/KEPGJFLJ.png",
    category: "상의",
    upgrade: 0,
    base: {
      str: 30,
      dex: 30,
      atk: 2,
      def: 135,
      ignoreDef: 5,
    },
    scroll: {
      str: 62,
      dex: 62,
      hp: 255,
      atk: 19,
      mAtk: 19,
      def: 187,
    },
    grade: "epic",
    star: 17,
    potential: {
      grade: "epic",
      effects: [
        {
          strP: 6,
        },
        {
          intP: 3,
        },
        {
          mp: 120,
        },
      ],
    },
    flame: {
      str: 32,
      atk: 3,
      mAtk: 3,
      allStatP: 3,
    },
    scissors: 10,
  },
  {
    name: "앱솔랩스 파이렛숄더",
    imageUrl: "https://avatar.maplestory.nexon.com/ItemIcon/KEOHJGJI.png",
    category: "어깨장식",
    upgrade: 0,
    base: {
      str: 14,
      dex: 14,
      int: 14,
      luk: 14,
      atk: 10,
      mAtk: 10,
      def: 100,
    },
    scroll: {
      str: 66,
      dex: 66,
      int: 26,
      luk: 26,
      hp: 255,
      atk: 21,
      mAtk: 21,
      def: 142,
    },
    grade: "epic",
    star: 17,
    potential: {
      grade: "epic",
      effects: [
        {
          strP: 6,
        },
        {
          int: 12,
        },
        {
          allStat: 5,
        },
      ],
    },
    flame: {},
  },
  {
    name: "블랙 리스트 아머",
    imageUrl: "https://avatar.maplestory.nexon.com/ItemIcon/KEMHJOOG.png",
    category: "리스트밴드",
    upgrade: 0,
    base: {
      str: 8,
      dex: 8,
      atk: 5,
    },
    scroll: {},
    grade: "unique",
    star: 0,
    potential: {
      grade: "unique",
      effects: [
        {
          atkP: 9,
        },
        {
          atkP: 6,
        },
        {
          dexP: 6,
        },
      ],
    },
    flame: {},
  },
  {
    name: "앱솔랩스 파이렛글러브",
    imageUrl: "https://avatar.maplestory.nexon.com/ItemIcon/KEPKJBKB.png",
    category: "장갑",
    upgrade: 0,
    base: {
      str: 20,
      dex: 20,
      atk: 5,
      def: 150,
    },
    scroll: {
      str: 66,
      dex: 66,
      atk: 28,
      mAtk: 21,
      def: 206,
    },
    grade: "epic",
    star: 17,
    potential: {
      grade: "epic",
      effects: [
        {
          strP: 6,
        },
        {
          strP: 3,
        },
        {
          def: 120,
        },
      ],
    },
    flame: {
      dex: 25,
      int: 25,
      atk: 3,
      jump: 4,
      allStatP: 5,
    },
    scissors: 10,
  },
  {
    name: "앱솔랩스 파이렛슈즈",
    imageUrl: "https://avatar.maplestory.nexon.com/ItemIcon/KEPFIHNE.png",
    category: "신발",
    upgrade: 0,
    base: {
      str: 20,
      dex: 20,
      atk: 5,
      def: 150,
      speed: 10,
      jump: 7,
    },
    scroll: {
      str: 66,
      dex: 66,
      atk: 21,
      mAtk: 21,
      def: 206,
      speed: 18,
      jump: 18,
    },
    grade: "epic",
    star: 17,
    potential: {
      grade: "epic",
      effects: [
        {
          str: 12,
        },
        {
          mp: 120,
        },
      ],
    },
    flame: {
      str: 25,
      int: 15,
      luk: 40,
      allStatP: 4,
    },
    scissors: 10,
  },
  {
    name: "이터널 플레임 링",
    imageUrl: "https://avatar.maplestory.nexon.com/ItemIcon/KEODPEMF.png",
    category: "반지",
    upgrade: 0,
    base: {
      str: 40,
      dex: 40,
      int: 40,
      luk: 40,
      hp: 4000,
      mp: 4000,
      atk: 25,
      mAtk: 25,
    },
    scroll: {},
    grade: "unique",
    star: 0,
    potential: {
      grade: "unique",
      effects: [
        {
          strP: 9,
        },
        {
          allStatP: 3,
        },
        {
          mpP: 6,
        },
      ],
    },
    flame: {},
  },
  {
    name: "하이네스 원더러햇",
    imageUrl: "https://avatar.maplestory.nexon.com/ItemIcon/KEPCIPOA.png",
    category: "모자",
    upgrade: 0,
    base: {
      str: 40,
      dex: 40,
      hp: 360,
      mp: 360,
      atk: 2,
      def: 300,
      ignoreDef: 10,
    },
    scroll: {
      str: 62,
      dex: 62,
      hp: 255,
      atk: 19,
      mAtk: 19,
      def: 402,
    },
    grade: "epic",
    star: 17,
    potential: {
      grade: "epic",
      effects: [
        {
          strP: 6,
        },
        {
          luk: 12,
        },
        {
          str: 12,
        },
      ],
    },
    flame: {
      str: 20,
      int: 20,
      luk: 40,
      hp: 2250,
      mp: 2250,
    },
    scissors: 10,
  },
  {
    name: "골드 메이플리프 엠블렘",
    imageUrl: "https://avatar.maplestory.nexon.com/ItemIcon/KEOLLEOA.png",
    category: "엠블렘",
    upgrade: 0,
    base: {
      str: 10,
      dex: 10,
      int: 10,
      luk: 10,
      atk: 2,
      mAtk: 2,
    },
    scroll: {},
    grade: "unique",
    star: 0,
    potential: {
      grade: "unique",
      effects: [
        {
          atkP: 9,
        },
        {
          lukP: 6,
        },
      ],
    },
    flame: {},
  },
  {
    name: "응축된 힘의 결정석",
    imageUrl: "https://avatar.maplestory.nexon.com/ItemIcon/KEPDJDJJ.png",
    category: "얼굴장식",
    upgrade: 0,
    base: {
      str: 5,
      dex: 5,
      int: 5,
      luk: 5,
      atk: 5,
      mAtk: 5,
      def: 100,
    },
    scroll: {
      str: 25,
      dex: 25,
      int: 25,
      luk: 25,
      def: 70,
    },
    grade: "epic",
    star: 10,
    potential: {
      grade: "epic",
      effects: [
        {
          strP: 6,
        },
        {
          luk: 12,
        },
        {
          strP: 3,
        },
      ],
    },
    flame: {
      int: 15,
      luk: 15,
      hp: 1650,
      atk: 3,
      def: 18,
    },
  },
  {
    name: "크리스탈 웬투스 뱃지",
    imageUrl: "https://avatar.maplestory.nexon.com/ItemIcon/KEOKJHGG.png",
    category: "뱃지",
    upgrade: 0,
    base: {
      str: 10,
      dex: 10,
      int: 10,
      luk: 10,
      atk: 5,
      mAtk: 5,
      speed: 10,
      jump: 10,
    },
    scroll: {},
    grade: "nothing",
    star: 0,
    flame: {},
  },
  {
    name: "블랙빈 마크",
    imageUrl: "https://avatar.maplestory.nexon.com/ItemIcon/KEPAJFND.png",
    category: "눈장식",
    upgrade: 0,
    base: {
      str: 7,
      dex: 7,
      int: 7,
      luk: 7,
      atk: 1,
      mAtk: 1,
      def: 120,
    },
    scroll: {
      str: 54,
      dex: 54,
      int: 54,
      luk: 54,
      atk: 15,
      mAtk: 15,
      def: 170,
    },
    grade: "unique",
    star: 17,
    potential: {
      grade: "unique",
      effects: [
        {
          hpHeal: 30,
        },
        {
          strP: 6,
        },
        {
          strP: 6,
        },
      ],
    },
    flame: {
      str: 32,
      dex: 16,
      int: 20,
      luk: 36,
      allStatP: 5,
    },
  },
  {
    name: "지옥의 불꽃",
    imageUrl: "https://avatar.maplestory.nexon.com/ItemIcon/KEPBJGNH.png",
    category: "귀고리",
    upgrade: 0,
    base: {
      str: 7,
      dex: 7,
      int: 7,
      luk: 7,
      hp: 100,
      mp: 100,
      atk: 2,
      mAtk: 2,
      def: 100,
    },
    scroll: {
      str: 25,
      dex: 25,
      int: 25,
      luk: 25,
      def: 70,
    },
    grade: "nothing",
    star: 10,
    flame: {
      dex: 24,
      luk: 24,
      hp: 1950,
      speed: 5,
      allStatP: 5,
    },
  },
  {
    name: "리부트 테네브리스 원정대 반지(완성)",
    imageUrl: "https://avatar.maplestory.nexon.com/ItemIcon/KEODPEPA.png",
    category: "반지",
    upgrade: 0,
    base: {
      str: 40,
      dex: 40,
      int: 40,
      luk: 40,
      hp: 4000,
      mp: 4000,
      atk: 25,
      mAtk: 25,
    },
    scroll: {},
    grade: "epic",
    star: 0,
    potential: {
      grade: "epic",
      effects: [
        {
          strP: 6,
        },
        {
          mp: 120,
        },
        {
          lukP: 3,
        },
      ],
    },
    flame: {},
  },
  {
    name: "앱솔랩스 블로우너클",
    imageUrl: "https://avatar.maplestory.nexon.com/ItemIcon/KELKJFMD.png",
    category: "너클 (두손무기)",
    upgrade: 0,
    base: {
      str: 60,
      dex: 60,
      atk: 154,
      bossDmg: 30,
      ignoreDef: 10,
    },
    scroll: {
      str: 66,
      dex: 66,
      hp: 255,
      mp: 255,
      atk: 81,
    },
    grade: "unique",
    star: 17,
    potential: {
      grade: "unique",
      effects: [
        {
          dmg: 9,
        },
        {
          bossDmg: 35,
        },
        {
          crit: 10,
        },
      ],
    },
    flame: {
      mp: 1440,
      atk: 47,
      def: 27,
      bossDmg: 10,
    },
  },
  {
    name: "이글아이 원더러코트",
    imageUrl: "https://avatar.maplestory.nexon.com/ItemIcon/KEPGJFLJ.png",
    category: "상의",
    upgrade: 0,
    base: {
      str: 30,
      dex: 30,
      atk: 2,
      def: 135,
      ignoreDef: 5,
    },
    scroll: {
      str: 62,
      dex: 62,
      hp: 255,
      atk: 19,
      mAtk: 19,
      def: 187,
    },
    grade: "epic",
    star: 17,
    potential: {
      grade: "epic",
      effects: [
        {
          strP: 6,
        },
        {
          intP: 3,
        },
        {
          mp: 120,
        },
      ],
    },
    flame: {
      str: 32,
      atk: 3,
      mAtk: 3,
      allStatP: 3,
    },
    scissors: 10,
  },
  {
    name: "앱솔랩스 파이렛숄더",
    imageUrl: "https://avatar.maplestory.nexon.com/ItemIcon/KEOHJGJI.png",
    category: "어깨장식",
    upgrade: 0,
    base: {
      str: 14,
      dex: 14,
      int: 14,
      luk: 14,
      atk: 10,
      mAtk: 10,
      def: 100,
    },
    scroll: {
      str: 66,
      dex: 66,
      int: 26,
      luk: 26,
      hp: 255,
      atk: 21,
      mAtk: 21,
      def: 142,
    },
    grade: "epic",
    star: 17,
    potential: {
      grade: "epic",
      effects: [
        {
          strP: 6,
        },
        {
          int: 12,
        },
        {
          allStat: 5,
        },
      ],
    },
    flame: {},
  },
  {
    name: "블랙 리스트 아머",
    imageUrl: "https://avatar.maplestory.nexon.com/ItemIcon/KEMHJOOG.png",
    category: "리스트밴드",
    upgrade: 0,
    base: {
      str: 8,
      dex: 8,
      atk: 5,
    },
    scroll: {},
    grade: "unique",
    star: 0,
    potential: {
      grade: "unique",
      effects: [
        {
          atkP: 9,
        },
        {
          atkP: 6,
        },
        {
          dexP: 6,
        },
      ],
    },
    flame: {},
  },
  {
    name: "앱솔랩스 파이렛글러브",
    imageUrl: "https://avatar.maplestory.nexon.com/ItemIcon/KEPKJBKB.png",
    category: "장갑",
    upgrade: 0,
    base: {
      str: 20,
      dex: 20,
      atk: 5,
      def: 150,
    },
    scroll: {
      str: 66,
      dex: 66,
      atk: 28,
      mAtk: 21,
      def: 206,
    },
    grade: "epic",
    star: 17,
    potential: {
      grade: "epic",
      effects: [
        {
          strP: 6,
        },
        {
          strP: 3,
        },
        {
          def: 120,
        },
      ],
    },
    flame: {
      dex: 25,
      int: 25,
      atk: 3,
      jump: 4,
      allStatP: 5,
    },
    scissors: 10,
  },
  {
    name: "앱솔랩스 파이렛슈즈",
    imageUrl: "https://avatar.maplestory.nexon.com/ItemIcon/KEPFIHNE.png",
    category: "신발",
    upgrade: 0,
    base: {
      str: 20,
      dex: 20,
      atk: 5,
      def: 150,
      speed: 10,
      jump: 7,
    },
    scroll: {
      str: 66,
      dex: 66,
      atk: 21,
      mAtk: 21,
      def: 206,
      speed: 18,
      jump: 18,
    },
    grade: "epic",
    star: 17,
    potential: {
      grade: "epic",
      effects: [
        {
          str: 12,
        },
        {
          mp: 120,
        },
      ],
    },
    flame: {
      str: 25,
      int: 15,
      luk: 40,
      allStatP: 4,
    },
    scissors: 10,
  },
];
