export const LOAD_MAPLE_CHRACTER_REQUEST = "MAPLE/LOAD_MAPLE_CHRACTER_REQUEST";
export const LOAD_MAPLE_CHRACTER_SUCCESS = "MAPLE/LOAD_MAPLE_CHRACTER_SUCCESS";
export const LOAD_MAPLE_CHRACTER_FAILURE = "MAPLE/LOAD_MAPLE_CHRACTER_FAILURE";
