export const AllOfStatName = {
    "str" : 0,
    "dex" : 0,
    "int" : 0,
    "luk" : 0,
    "hp" : 0,
    "mp" : 0,
    "atk" : 0,
    "mAtk" : 0,
    "def" : 0,
    "speed" : 0,
    "jump" : 0,
    "ignoreDef" : 0,
    "ignoreDefArr" : [],
    "mobDmg" : 0,
    "bossDmg" : 0,
    "dmg" : 0,
    "allStat" : 0,
    "crit" : 0,
    "critDmg" : 0,
    "meso" : 0,
    "drop" : 0,
    "reuse" : 0,
}

export const AllOfStatNameWithPersent = {
    "strP" : 0,
    "dexP" : 0,
    "intP" : 0,
    "lukP" : 0,
    "hpP" : 0,
    "mpP" : 0,
    "atkP" : 0,
    "mAtkP" : 0,
    "defP" : 0,
    "allStatP" : 0,
}